-- Script completo para criar a tabela categories e adicionar category_id aos produtos
-- Execute este script no SQL Editor do Supabase

-- 1. Criar a tabela categories
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    name TEXT NOT NULL UNIQUE,
    slug TEXT NOT NULL UNIQUE
);

-- 2. Habilitar RLS para categories
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

-- 3. Criar políticas para categories
DROP POLICY IF EXISTS "Allow public read access" ON public.categories;
DROP POLICY IF EXISTS "Allow authenticated insert" ON public.categories;
DROP POLICY IF EXISTS "Allow authenticated update" ON public.categories;
DROP POLICY IF EXISTS "Allow authenticated delete" ON public.categories;

CREATE POLICY "Allow public read access" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Allow authenticated insert" ON public.categories FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated update" ON public.categories FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated delete" ON public.categories FOR DELETE USING (auth.role() = 'authenticated');

-- 4. Adicionar a coluna category_id à tabela products
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND table_name = 'products' 
        AND column_name = 'category_id'
    ) THEN
        ALTER TABLE public.products 
        ADD COLUMN category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL;
        
        RAISE NOTICE 'Coluna category_id adicionada com sucesso!';
    ELSE
        RAISE NOTICE 'Coluna category_id já existe.';
    END IF;
END $$;

-- Pronto! Agora você pode usar o menu de Categorias no admin panel
