-- 1. Garante que a tabela collections existe
CREATE TABLE IF NOT EXISTS public.collections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    image TEXT NOT NULL,
    description TEXT
);

-- 2. Adiciona colunas que podem estar faltando
DO $$
BEGIN
    ALTER TABLE public.collections ADD COLUMN IF NOT EXISTS image TEXT;
    ALTER TABLE public.collections ADD COLUMN IF NOT EXISTS description TEXT;
    ALTER TABLE public.collections ADD COLUMN IF NOT EXISTS slug TEXT;
EXCEPTION
    WHEN duplicate_column THEN RAISE NOTICE 'column already exists';
END $$;

-- 3. Reseta as permissões de collections
DROP POLICY IF EXISTS "Allow public read access" ON public.collections;
DROP POLICY IF EXISTS "Allow authenticated insert" ON public.collections;
DROP POLICY IF EXISTS "Allow authenticated update" ON public.collections;
DROP POLICY IF EXISTS "Allow authenticated delete" ON public.collections;

ALTER TABLE public.collections ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" ON public.collections FOR SELECT USING (true);
CREATE POLICY "Allow authenticated insert" ON public.collections FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated update" ON public.collections FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated delete" ON public.collections FOR DELETE USING (auth.role() = 'authenticated');

-- Create products table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    name TEXT NOT NULL,
    brand TEXT NOT NULL DEFAULT 'Conexão 011',
    price NUMERIC NOT NULL,
    images TEXT[] NOT NULL DEFAULT '{}',
    category TEXT NOT NULL,
    sizes JSONB NOT NULL DEFAULT '[]',
    description TEXT,
    slug TEXT NOT NULL UNIQUE,
    collection_id BIGINT REFERENCES public.collections(id) ON DELETE SET NULL
);

-- Enable Row Level Security for products
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- Create policies for products
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'products' AND policyname = 'Allow public read access'
    ) THEN
        CREATE POLICY "Allow public read access" ON public.products
            FOR SELECT
            USING (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'products' AND policyname = 'Allow authenticated insert'
    ) THEN
        CREATE POLICY "Allow authenticated insert" ON public.products
            FOR INSERT
            WITH CHECK (auth.role() = 'authenticated');
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'products' AND policyname = 'Allow authenticated update'
    ) THEN
        CREATE POLICY "Allow authenticated update" ON public.products
            FOR UPDATE
            USING (auth.role() = 'authenticated');
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'products' AND policyname = 'Allow authenticated delete'
    ) THEN
        CREATE POLICY "Allow authenticated delete" ON public.products
            FOR DELETE
            USING (auth.role() = 'authenticated');
    END IF;
END
$$;

-- Create storage bucket for images if it doesn't exist
INSERT INTO storage.buckets (id, name, public)
VALUES ('images', 'images', true)
ON CONFLICT (id) DO NOTHING;

-- Create storage policies
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'objects' AND policyname = 'Give public access to images'
    ) THEN
        CREATE POLICY "Give public access to images" ON storage.objects
            FOR SELECT
            USING (bucket_id = 'images');
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'objects' AND policyname = 'Allow authenticated uploads'
    ) THEN
        CREATE POLICY "Allow authenticated uploads" ON storage.objects
            FOR INSERT
            WITH CHECK (bucket_id = 'images' AND auth.role() = 'authenticated');
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'objects' AND policyname = 'Allow authenticated updates'
    ) THEN
        CREATE POLICY "Allow authenticated updates" ON storage.objects
            FOR UPDATE
            USING (bucket_id = 'images' AND auth.role() = 'authenticated');
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'objects' AND policyname = 'Allow authenticated deletes'
    ) THEN
        CREATE POLICY "Allow authenticated deletes" ON storage.objects
            FOR DELETE
            USING (bucket_id = 'images' AND auth.role() = 'authenticated');
    END IF;
END
$$;
